import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "./components/navbar";
import { LayoutBody } from "./layoutBody";

import "./styles/index.scss";
import "./styles/layout.scss";
import "./styles/spacing.scss";
import "./styles/buttons.scss";
import "./styles/sizings.scss";
import "./styles/color.scss";
import "./styles/text.scss";
import { LayoutHead } from "./layoutHead";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords:
    "Laptops, Macbooks, Computers, PCs, Personal, Best computer, cheap computer, cheap laptop, budget laptop, best laptop",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LayoutHead />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LayoutBody children={children} />
      </body>
    </html>
  );
}
